name: Shell Commands
#👆 this is the name of our entire workflow

on: [push]
#👆 this will trigger an events like(push, pull_request) which run this entire workflow

#👇 each workflow has one or more jobs
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world"
      - name: multiline script
        run: |
          node -v
          npm -v
